UrbanCCD-UChicago/plenario

Dockerfile, plenario/settings.py.docker
I was playing around with the Docker config on my own fork before I had push access. Unfortunately, the old Dockerfile didn't keep up with new project dependencies. This still isn't fully functioning, but it's a step closer. I'm going to revisit it later.
Thanks to @hunterowens for the original!
=> Update development Dockerfile

plenario/static/js/backbone.js, plenario/static/js/explore/app.js, plenario/static/js/explore/collections/shapes.js, plenario/static/js/explore/helpers.js, plenario/static/js/explore/models/shape.js, plenario/static/js/explore/router.js, plenario/static/js/explore/templates/shapesList.html, plenario/static/js/explore/views/about-view.js, plenario/static/js/explore/views/map-view.js, plenario/static/js/explore/views/shapeView.js, plenario/static/js/jquery-1.11.3.js, plenario/static/js/underscore.js, plenario/templates/base.html, plenario/templates/explore.html
Display available shape datasets and render available shape datasets and numbers of shapes within the geo location in response to a query.
=> Shape frontend

plenario/etl/common.py
=> Download ETL files in 1MB chunks

.codeclimate.yml, .travis.yml, README.md, init_db.py, plenario/api/point.py, tests/points/point_etl_tests.py, tests/points/points_tests.py
Doing this as a PR instead of just merging so I can check out the PR integration.
=> Add Travis testing and Codeclimate linting

plenario/static/js/explore/collections/shapes.js, plenario/static/js/explore/templates/shapeDetailTemplate.html, plenario/static/js/explore/templates/shapesList.html
Rendering more details about the dataset such as attribution and description and also provide explanation for not rendering large datasets
=> more details and explanation

plenario/api/__init__.py, plenario/api/shape.py, plenario/templates/api-docs.html, plenario/utils/ogr2ogr.py, tests/shapes/shape_tests.py
Modified ogr2ogr export util to allow general sql querying for a new 'filter' api for shapes. 'Also includes two unit tests and api docs.
=> Shape filter

plenario/api/point.py, tests/points/api_tests.py, tests/shapes/shape_tests.py
New point API tests for detail query with new JSON and csv export methods; refactoring of 'detail' API into helper functions
=> Detail cleanup

plenario/templates/explore.html
=> update explore.html links to CDN hosted files (for speed)

plenario/api/point.py, tests/points/api_tests.py
Keeps updated "/fields" while maintaining original JSON response
=> corrected fields JSON response and fields test

plenario/api/condition_builder.py, plenario/api/point.py, plenario/api/response.py, plenario/api/shape.py, plenario/api/validator.py, plenario/models.py, tests/points/api_tests.py, tests/points/validator_tests.py, tests/shapes/shape_tests.py
In this PR I've added support for a JSON Patch-like syntax which allows users to make more complicated queries, specifically with dataset column conditions. There are a lot of changes, and while I'm enthusiastic about that I realize it makes this really tough to review. Instead of listing the changes here, I'm going to comment up all the files -- hopefully this makes things easier. In the future I'll keep the the PRs smaller in scale.
=> Adding support for tree filters

plenario/models.py, tests/shapes/shape_tests.py
Adds column information to shape dataset metadata
=> Add column metadata to /shapes

plenario/api/point.py, plenario/api/validator.py, tests/points/validator_tests.py
=> Fix an issue where Validator would throw out valid date arguments because they were not obs_date

init_db.py, plenario/utils/weather_metar.py, runserver.py
Update metar failed because it did not have a call_sign_wban_map to look up.
=> Fix update_metar

.travis.yml, init_db.py, plenario/__init__.py, plenario/api/__init__.py, plenario/apiary/admin_view.py, plenario/apiary/views.py, plenario/dbscripts/sensors_trigger.sql, plenario/models/SensorNetwork.py, plenario/sensor_network/api/sensor_aggregate_functions.py, plenario/sensor_network/api/sensor_networks.py, plenario/sensor_network/api/sensor_response.py, plenario/settings.py, plenario/tasks.py, plenario/templates/explore.html, plenario/templates/index.html, requirements.txt, tests/test_sensor_network/fixtures.py, tests/test_sensor_network/test_nearest.py, tests/test_sensor_network/test_sensor_networks.py, tests/test_tasks/test_archive.py
Pull in multinetwork support and a handful of bugfixes
=> Multinetwork without disclaimer

plenario/etl/point.py
Allows ETL process to adapt to datasets which add or remove columns
=> Drop and replace etl

plenario/sensor_network/api/sensor_networks.py
Enable filtering on feature properties for the nearest neighbor endpoint
=> Nearest ifttt

plenario/models/MetaTable.py, tests/test_api/test_point.py
Fix timeseries bucket format regression
=> Timeries bucket format

plenario/api/point.py
=> Reverse search when looking for condition trees

plenario/models/MetaTable.py
https://postgis.net/docs/ST_SnapToGrid.html
Making use of the origin arguments lets us attain grids that overlap cleanly if a geom is provided.
Nice catch! @brlodi
=> Snap grid alignment to geom if provided!

plenario/models/MetaTable.py
An attempt to address minor grid misalignments that seem to be a result of rounding errors during geom centroid calculation
=> Set grid origin to 0, 0
